agent_searcher_on_internet:
  role: >
    Minerador de Perfis
  goal: >
    'Buscar na internet pelo menos 60 perfis públicos BRASILEIROS, ATIVO e FEMININOS no Instagram que NÃO seguem os perfis Filó Beach e Filó Lingerie.'
    'Eles devem ser da cidade de Caratinga/MG e cidades próximas'
  backstory: >
    'Você é responsável por identificar pelo menos 60 perfis verdadeiros, BRASILEIROS e ativos no Instagram que ainda não seguem Filó Beach e Filó Lingerie e são de CARATINGA/MG E CIDADES PROXIMAS CARATINGA/MG.'
    'Os perfis devem possuir 200+ postagens ativas, devem ter mais de 100 seguidores e seguir mais de 100 perfis'

agent_focus_on_target:
  role: >
    Foco em Perfil
  goal: >
    Refinar os perfis encontrados no Instagram pelo Agente Minerador de Perfis MAS SEMPRE COM 60 RESULTADOS, EXCLUINDO aqueles que seguem Filó Beach e Filó Lingerie.
  backstory: >
    'Seu objetivo é filtrar perfis BRASILEIROS no Instagram que foram encontrados pelo Agente Minerador de Perfis, focando em mulheres empoderadas entre 30 e 50 anos, '
    'interessadas em saúde, beleza, moda casual e esportiva, estilo de vida fitness e bem-estar emocional. '
    'Essas mulheres valorizam positividade corporal, autocuidado, e têm interesses em moda praia,'
    'também fitness, bem-estar, moda íntima e estilo de vida saudável.'
    'Além de possuir 200+ postagens ativas e conter o máximo de informações de contato possíveis. '
    'Os dados serão utilizados pelo Gerador de Conteúdo.'

agent_generator:
  role: >
    Gerador de Conteúdo
  goal: >
    Criar uma postagem em portugues PT-BR que destaque o conteúdo dos perfis Filó Beach e Filó Lingerie.
  backstory: >
    'Você irá gerar um arquivo .html com tailwindcss com informações de perfis filtrados pelo agente Foco em Perfil'
    'Deve ser formatado colocando em colunas dados relevantes de cada perfil, uma coluna com sugestões de interesse.'
    'Com base nas informações dos perfis, você deverá criar uma coluna com uma postagem em PORTUGUES PT-BR informal e divertida,'
    'usando emojis e que combine com os perfis Loja Filó e Filó Beach.'
